### ISSUE TITLE
NullPointerException when running against Kubernetes 1.5.2

### ISSUE THREAD

**Issue by RemonSinnema** [spring-cloud/spring-cloud-deployer-kubernetes#103]
2017-02-10 08:29:55.395 DEBUG 1 --- [nio-9393-exec-9] o.s.c.d.s.k.AbstractKubernetesDeployer   : Deploying app: xxx
2017-02-10 08:29:58.748 DEBUG 1 --- [nio-9393-exec-9] o.s.c.d.s.k.AbstractKubernetesDeployer   : Building AppStatus for app: xxx
2017-02-10 08:29:58.763 ERROR 1 --- [nio-9393-exec-9] o.s.c.d.s.k.AbstractKubernetesDeployer   : null

java.lang.NullPointerException: null
	at org.springframework.cloud.deployer.spi.kubernetes.KubernetesAppDeployer.status(KubernetesAppDeployer.java:174) ~[spring-cloud-deployer-kubernetes-1.0.4.RELEASE.jar!/:1.0.4.RELEASE]
	at org.springframework.cloud.deployer.spi.kubernetes.KubernetesAppDeployer.deploy(KubernetesAppDeployer.java:79) ~[spring-cloud-deployer-kubernetes-1.0.4.RELEASE.jar!/:1.0.4.RELEASE]
	at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.deployStream(StreamDeploymentController.java:250) [spring-cloud-dataflow-server-core-1.0.1.RELEASE.jar!/:1.0.1.RELEASE]
	at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.deploy(StreamDeploymentController.java:186) [spring-cloud-dataflow-server-core-1.0.1.RELEASE.jar!/:1.0.1.RELEASE]

**Comment by RemonSinnema** [comment]
Probably a duplicate of #97.
