### ISSUE TITLE
Fabric8 version misalignment

### ISSUE THREAD

**Issue by TYsewyn** [spring-cloud/spring-cloud-deployer-kubernetes#511]
This project adds version `5.12.2` of the Fabric8 K8s client while it also pulls in version `5.10.2` for the other Fabric8 libraries via `spring-cloud-deployer-parent:2.8.0-RC1` -> `spring-cloud-dataflow-build:2.10.0-RC1` -> `spring-cloud-dataflow-build-dependencies:2.10.0-RC1` -> `spring-cloud-dependencies:2021.0.3` -> `spring-cloud-kubernetes-dependencies:2.1.3` -> `kubernetes-client-bom:5.10.2`.

Added this dependency to a Spring Boot application with version `3.0.0.RC1`.

See following stacktrace:
```
jakarta.servlet.ServletException: Handler dispatch failed: java.lang.NoSuchMethodError: 'io.fabric8.kubernetes.api.model.Handler io.fabric8.kubernetes.api.model.Lifecycle.getPostStart()'
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1095) ~[spring-webmvc-6.0.0-RC2.jar:6.0.0-RC2]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973) ~[spring-webmvc-6.0.0-RC2.jar:6.0.0-RC2]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1003) ~[spring-webmvc-6.0.0-RC2.jar:6.0.0-RC2]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:906) ~[spring-webmvc-6.0.0-RC2.jar:6.0.0-RC2]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:709) ~[tomcat-embed-core-10.0.27.jar:5.0.0]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:880) ~[spring-webmvc-6.0.0-RC2.jar:6.0.0-RC2]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:792) ~[tomcat-embed-core-10.0.27.jar:5.0.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223) ~[tomcat-embed-core-10.0.27.jar:10.0.27]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.0.27.jar:10.0.27]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-10.0.27.jar:10.0.27]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.0.27.jar:10.0.27]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.0.27.jar:10.0.27]
        at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88) ~[spring-boot-actuator-3.0.0-RC1.jar:3.0.0-RC1]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.0-RC2.jar:6.0.0-RC2]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.0.27.jar:10.0.27]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.0.27.jar:10.0.27]
        at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231) ~[spring-security-web-6.0.0-RC1.jar:6.0.0-RC1]
        at org.springframework.security.web.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:394) ~[spring-security-web-6.0.0-RC1.jar:6.0.0-RC1]
        at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:292) ~[spring-security-web-6.0.0-RC1.jar:6.0.0-RC1]
...
Caused by: java.lang.NoSuchMethodError: 'io.fabric8.kubernetes.api.model.Handler io.fabric8.kubernetes.api.model.Lifecycle.getPostStart()'
        at org.springframework.cloud.deployer.spi.kubernetes.AbstractKubernetesDeployer.createPodSpec(AbstractKubernetesDeployer.java:235) ~[spring-cloud-deployer-kubernetes-2.8.0-RC1.jar:2.8.0-RC1]
        at org.springframework.cloud.deployer.spi.kubernetes.KubernetesTaskLauncher.launch(KubernetesTaskLauncher.java:247) ~[spring-cloud-deployer-kubernetes-2.8.0-RC1.jar:2.8.0-RC1]
        at org.springframework.cloud.deployer.spi.kubernetes.KubernetesTaskLauncher.launch(KubernetesTaskLauncher.java:123) ~[spring-cloud-deployer-kubernetes-2.8.0-RC1.jar:2.8.0-RC1]
        at 
...
```

**Comment by onobc** [comment]
**NOTES:**
- It was changed https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/commit/030048c23c3beb443f588beff497dd660d13cc33 to support startup probes. Hopefully this is easy to override via `dependencyManagement` for the fabric8 deps in https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-kubernetes-dependencies/2.1.5
