### ISSUE TITLE
Cannot deploy to Kubernetes v1.5.1 cluster

### ISSUE THREAD

**Issue by RemonSinnema** [spring-cloud/spring-cloud-deployer-kubernetes#97]
I've upgraded my cluster to Kubernetes 1.5.1 (from 1.4.4) and I'm now getting the following exception when deploying streams using SCDF `1.0.1.RELEASE`:

```
2016-12-21 08:40:36.938 DEBUG 1 --- [io-9393-exec-10] o.s.c.d.s.k.AbstractKubernetesDeployer   : Deploying app: xxx
2016-12-21 08:40:37.767 DEBUG 1 --- [io-9393-exec-10] o.s.c.d.s.k.AbstractKubernetesDeployer   : Building AppStatus for app: xxx
2016-12-21 08:40:37.783 ERROR 1 --- [io-9393-exec-10] o.s.c.d.s.k.AbstractKubernetesDeployer   : null
java.lang.NullPointerException: null
	at org.springframework.cloud.deployer.spi.kubernetes.KubernetesAppDeployer.status(KubernetesAppDeployer.java:174) ~[spring-cloud-deployer-kubernetes-1.0.4.RELEASE.jar!/:1.0.4.RELEASE]
	at org.springframework.cloud.deployer.spi.kubernetes.KubernetesAppDeployer.deploy(KubernetesAppDeployer.java:79) ~[spring-cloud-deployer-kubernetes-1.0.4.RELEASE.jar!/:1.0.4.RELEASE]
	at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.deployStream(StreamDeploymentController.java:250) [spring-cloud-dataflow-server-core-1.0.1.RELEASE.jar!/:1.0.1.RELEASE]
	at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.deploy(StreamDeploymentController.java:186) [spring-cloud-dataflow-server-core-1.0.1.RELEASE.jar!/:1.0.1.RELEASE]
```

The `status()` method doesn't handle the situation where not a single pod is scheduled for the stream, which is the real problem. I verified this with `kubectl get pod`.

After downgrading the cluster to Kubernetes v1.4.7 everything works as expected again.

**Comment by trisberg** [comment]
Looking at Google Cloud Platform, the most recent version I see is 1.4.7, is his your own install?

**Comment by trisberg** [comment]
You could try with the more recent Data Flow 1.1.0 release, should have a more recent Fabric8 client version, although it might still not work with Kubernetes 1.5.x.

**Comment by RemonSinnema** [comment]
[Kubernetes 1.5](http://blog.kubernetes.io/2016/12/kubernetes-1.5-supporting-production-workloads.html) was released on 2016-12-13; see the [releases](https://github.com/kubernetes/kubernetes/releases/) page.

I'm having some issues with 1.1.0, but I'll see if I can figure them out.

However, looking at the latest code for the above stack trace, I'm quite confident that the `NullPointerException` issue will still be there whenever SCDF fails to deploy a pod for a stream app.

**Comment by trisberg** [comment]
Yes, I'm now able to reproduce a NPE using minikube v1.5.1, should have a fix soon

**Comment by trisberg** [comment]
I've built a snapshot version that uses the new deployer. Could you test it out and let me know if it works? I'v uploaded the image to Docker Hub.

```
    image: trisberg/spring-cloud-dataflow-server-kubernetes:latest
```

**Comment by RemonSinnema** [comment]
The fix doesn't work for me. I get

```
java.lang.NullPointerException: null
	at org.springframework.cloud.deployer.spi.kubernetes.KubernetesAppDeployer.status(KubernetesAppDeployer.java:178) ~[spring-cloud-deployer-kubernetes-1.1.1.BUILD-SNAPSHOT.jar!/:1.1.1.BUILD-SNAPSHOT]
	at org.springframework.cloud.deployer.spi.kubernetes.KubernetesAppDeployer.deploy(KubernetesAppDeployer.java:76) ~[spring-cloud-deployer-kubernetes-1.1.1.BUILD-SNAPSHOT.jar!/:1.1.1.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.deployStream(StreamDeploymentController.java:244) [spring-cloud-dataflow-server-core-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
	at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.deploy(StreamDeploymentController.java:180) [spring-cloud-dataflow-server-core-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
```

It seems that line 178 of `KubernetesAppDeployer` needs another null check on `getItems()`. And maybe line 120 as well?

**Comment by trisberg** [comment]
Thanks for the feedback. Looks like that only happens with DEBUG logging turned on. I've built a new version top avoid that, if you get a chance to try that and verify it works on your cluster then I can wrap this up and release a 1.1.1.RELEASE. Same image URI `trisberg/spring-cloud-dataflow-server-kubernetes:latest`

**Comment by RemonSinnema** [comment]
Yes, I have `DEBUG` logging turned on.

With your latest changes, the `NullPointerException` is gone.

**Comment by trisberg** [comment]
Great, tanks again for the feedback. I'm planning on releasing 1.1.1.RELEASE of the Kubernetes deployer and the dataflow-server later today or early tomorrow unless we find some other issues.
